/* ─────────────────────────────────────────────
   Player ability catalog — purchased with gold,
   used in combat with energy.
   ───────────────────────────────────────────── */

const ABILITY_CATALOG = [
  {
    id: 'ab_strike',
    name: 'Power Strike',
    icon: '⚔️',
    type: 'attack',
    description: 'A direct blow. Always available, even when stunned.',
    energyCost: 10,
    reqLevel: 1,
    goldCost: 0,
    effect: { baseDmgMult: 1.0 },
  },
  {
    id: 'ab_heavy_blow',
    name: 'Heavy Blow',
    icon: '🔨',
    type: 'attack',
    description: 'A crushing strike that deals 1.8× base damage.',
    energyCost: 20,
    reqLevel: 3,
    goldCost: 60,
    effect: { baseDmgMult: 1.8 },
  },
  {
    id: 'ab_vampiric_strike',
    name: 'Vampiric Strike',
    icon: '🩸',
    type: 'attack',
    description: 'Deals 1.2× damage and heals you for 50% of damage dealt (max 25 HP).',
    energyCost: 25,
    reqLevel: 10,
    goldCost: 130,
    effect: { baseDmgMult: 1.2, healPct: 0.5, healMax: 25 },
  },
  {
    id: 'ab_healing_surge',
    name: 'Healing Surge',
    icon: '💚',
    type: 'heal',
    description: 'Restore 30 HP immediately.',
    energyCost: 30,
    reqLevel: 12,
    goldCost: 160,
    effect: { healFlat: 30 },
  },
  {
    id: 'ab_poison_dart',
    name: 'Poison Dart',
    icon: '🪃',
    type: 'poison',
    description: 'Poisons the enemy for 3 turns (8 damage per monster turn).',
    energyCost: 15,
    reqLevel: 5,
    goldCost: 80,
    effect: { applyToMonster: { type: 'poison', ticksRemaining: 3, damagePerTick: 8 } },
  },
  {
    id: 'ab_stun_strike',
    name: 'Stun Strike',
    icon: '⚡',
    type: 'stun',
    description: 'Deals 0.5× damage and stuns the enemy, causing them to skip their next turn.',
    energyCost: 25,
    reqLevel: 7,
    goldCost: 100,
    effect: { baseDmgMult: 0.5, applyToMonster: { type: 'stun', ticksRemaining: 1 } },
  },
  {
    id: 'ab_armor_break',
    name: 'Armor Break',
    icon: '🛡️',
    type: 'def_down',
    description: 'Deals 0.7× damage and shatters the enemy\'s armor — they take 40% more damage for 2 turns.',
    energyCost: 18,
    reqLevel: 6,
    goldCost: 90,
    effect: { baseDmgMult: 0.7, applyToMonster: { type: 'def_down', ticksRemaining: 2, mult: 1.4 } },
  },
  {
    id: 'ab_rally',
    name: 'Rally',
    icon: '🛡',
    type: 'def_up',
    description: 'Raise your defenses — take 40% less damage for 2 turns.',
    energyCost: 15,
    reqLevel: 4,
    goldCost: 70,
    effect: { applyToSelf: { type: 'def_up', ticksRemaining: 2, mult: 0.6 } },
  },
  {
    id: 'ab_battle_fury',
    name: 'Battle Fury',
    icon: '🔥',
    type: 'dmg_up',
    description: 'Enter a fury state — deal 60% more damage for 1 turn.',
    energyCost: 20,
    reqLevel: 8,
    goldCost: 110,
    effect: { applyToSelf: { type: 'dmg_up', ticksRemaining: 1, mult: 1.6 } },
  },
  {
    id: 'ab_exhaust_cry',
    name: 'War Cry',
    icon: '📯',
    type: 'exhaust',
    description: 'Cut the enemy\'s damage output in half for 2 turns.',
    energyCost: 22,
    reqLevel: 9,
    goldCost: 120,
    effect: { applyToMonster: { type: 'dmg_down', ticksRemaining: 2, mult: 0.5 } },
  },
  {
    id: 'ab_cripple',
    name: 'Cripple',
    icon: '🦴',
    type: 'exhaust',
    description: 'Cripple the enemy — they deal 30% less damage for 3 turns.',
    energyCost: 20,
    reqLevel: 11,
    goldCost: 140,
    effect: { applyToMonster: { type: 'dmg_down', ticksRemaining: 3, mult: 0.7 } },
  },
  {
    id: 'ab_cleanse',
    name: 'Cleanse',
    icon: '✨',
    type: 'cleanse',
    description: 'Remove all negative status effects (poison, stun, exhaust, dmg_down, def_down).',
    energyCost: 12,
    reqLevel: 6,
    goldCost: 85,
    effect: { removePlayerStatuses: ['poison', 'stun', 'exhaust', 'dmg_down', 'def_down'] },
  },
];
